# Generated by Django 6.0.4 on 2026-04-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Judul Jurnal')),
                ('abstract', models.TextField(blank=True, verbose_name='ringkasan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan ke Manager'), ('approved', 'Disetujui Manager'), ('rejected', 'Ditolak Manager'), ('uploaded', 'Jurnal Diupload'), ('under_review', 'Sedang Diverifikasi Admin'), ('revision_needed', 'Perlu Revisi'), ('verified', 'Diverifikasi Admin'), ('ready_scoring', 'Siap Dinilai')], default='draft', max_length=20, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='journals/%Y/%m/', verbose_name='File Jurnal (PDF)')),
                ('revision_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Revisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnal',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor (Penulis)'), ('manager', 'Manager (Approver)'), ('admin', 'Admin (Helpdesk)'), ('scoring', 'Scoring (Penilai)'), ('superadmin', 'Super Admin')], max_length=20)),
                ('manager', models.ForeignKey(blank=True, help_text='Atasan langsung (hanya untuk Supervisor)', limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='journal.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='JournalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Aksi')),
                ('note', models.TextField(blank=True, verbose_name='Catatan')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='journal.journal')),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journal.userprofile'),
        ),
    ]
