# Generated by Django 6.0.4 on 2026-04-27 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Publikasi'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan ke Manager'), ('approved', 'Disetujui Manager'), ('rejected', 'Ditolak Manager'), ('uploaded', 'Jurnal Diupload'), ('under_review', 'Sedang Diverifikasi Admin'), ('revision_needed', 'Perlu Revisi'), ('verified', 'Diverifikasi Admin'), ('scoring', 'Sedang Dinilai'), ('score_revision', 'Revisi dari Scoring'), ('recommended', 'Direkomendasikan'), ('not_recommended', 'Tidak Direkomendasikan'), ('published', 'Dipublikasikan')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='JournalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Orisinalitas (1-100)')),
                ('methodology', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Metodologi (1-100)')),
                ('writing_quality', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Kualitas Penulisan (1-100)')),
                ('relevance', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Relevansi (1-100)')),
                ('note', models.TextField(blank=True, verbose_name='Catatan Penilai')),
                ('recommendation', models.CharField(choices=[('recommend', 'Layak Dipublikasikan'), ('revision', 'Perlu Revisi'), ('reject', 'Tidak Layak')], max_length=20, verbose_name='Rekomendasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='journal.journal')),
                ('scorer', models.ForeignKey(limit_choices_to={'role': 'scoring'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
