# Generated by Django 4.2.30 on 2026-04-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_published_at_alter_journal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='abstract_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ringkasan Terakhir Diubah'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan ke Leader'), ('approved', 'Disetujui Leader'), ('rejected', 'Ditolak Leader'), ('uploaded', 'Jurnal Diupload'), ('under_review', 'Sedang Diverifikasi Admin'), ('revision_needed', 'Perlu Revisi'), ('verified', 'Diverifikasi Admin'), ('scoring', 'Sedang Dinilai'), ('score_revision', 'Revisi dari Scoring'), ('recommended', 'Direkomendasikan'), ('not_recommended', 'Tidak Direkomendasikan'), ('published', 'Dipublikasikan')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Atasan langsung (hanya untuk Writer)', limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='journal.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Writer (Penulis)'), ('manager', 'Leader (Approver)'), ('admin', 'Admin (Helpdesk)'), ('scoring', 'Scoring (Penilai)'), ('superadmin', 'Super Admin')], max_length=20),
        ),
    ]
