# Generated by Django 4.2.30 on 2026-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan ke Leader'), ('approved', 'Disetujui Leader'), ('rejected', 'Ditolak Leader'), ('uploaded', 'Menunggu Review File Leader'), ('under_review', 'Dikumpulkan Admin'), ('revision_needed', 'Perlu Revisi'), ('verified', 'Diverifikasi Admin'), ('scoring', 'Sedang Dinilai'), ('score_revision', 'Revisi dari Scoring'), ('under_recommendation', 'Menunggu Tim Rekomendasi'), ('recommended', 'Direkomendasikan'), ('not_recommended', 'Tidak Direkomendasikan'), ('published', 'Dipublikasikan')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Writer (Penulis)'), ('manager', 'Leader (Approver)'), ('admin', 'Admin (Helpdesk)'), ('scoring', 'Scoring (Penilai)'), ('recommendation', 'Recommendation (Tim Rekomendasi)'), ('superadmin', 'Super Admin')], max_length=20),
        ),
    ]
