# Generated by Django 4.2.30 on 2026-05-04 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_userprofile_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalscore',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='journalscore',
            name='originality',
        ),
        migrations.RemoveField(
            model_name='journalscore',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='journalscore',
            name='writing_quality',
        ),
        migrations.AddField(
            model_name='journalscore',
            name='positive_impact',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Dampak Positif (0-100)'),
        ),
        migrations.AddField(
            model_name='journalscore',
            name='problem_clarity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Identifikasi Masalah (0-100)'),
        ),
        migrations.AddField(
            model_name='journalscore',
            name='risk_awareness',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Identifikasi Risiko (0-100)'),
        ),
        migrations.AddField(
            model_name='journalscore',
            name='solution_quality',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Kualitas Solusi (0-100)'),
        ),
        migrations.AddField(
            model_name='journalscore',
            name='writing_clarity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Kejelasan Penulisan (0-100)'),
        ),
    ]
